### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by murraa** [studiousgamer/Jottley#1]

**Comment by natyavidhan** [comment]
## if you are trying to use the platform
- go to the home page [(here)](https://jottley.up.railway.app)
- make an account if you do not have, with google or discord
- make books, inside them chapters, inside them snippets of text in which you can store your text

## if you want to edit code or/and run locally
- first clone the repository in your drive: `git clone https://github.com/Project-WebChunk/Jottley`
- open terminal in the cloned folder
- make a virtual environment with `python -m venv env`
- activate the environment with `./env/scripts/activate`
- install requirements with `pip install -r requirements.txt`
- then run the app.py with `python app.py`
